export const CATEGORIES = [
  { id: "Favoriler", icon: "★", color: "#ffd45a" },
  { id: "Yapay Zekâ", icon: "✦", color: "#a788ff" },
  { id: "İş & Notlar", icon: "▤", color: "#67a9ff" },
  { id: "Geliştirme", icon: "⌘", color: "#91a0b6" },
  { id: "İletişim", icon: "●", color: "#55d787" },
  { id: "Seyahat", icon: "✈", color: "#63c7f4" },
  { id: "Haritalar", icon: "⌖", color: "#67d99b" },
  { id: "Medya", icon: "▶", color: "#ff6f91" },
  { id: "Yaratıcılık", icon: "◆", color: "#d58cff" },
  { id: "Google", icon: "G", color: "#6aa8ff" },
  { id: "Sistem", icon: "◉", color: "#aeb8c7" },
  { id: "Araçlar", icon: "⌁", color: "#59c9cd" },
  { id: "Alışveriş", icon: "▱", color: "#ff9b58" },
  { id: "Finans", icon: "₺", color: "#5dd18a" },
  { id: "Sosyal", icon: "@", color: "#ff718b" },
  { id: "Oyunlar", icon: "✣", color: "#ffcc4d" },
  { id: "Akıllı Ev", icon: "⌂", color: "#74cfff" },
  { id: "Uzaktan Erişim", icon: "⇄", color: "#8d93ff" },
  { id: "Linux", icon: "🐧", color: "#f47421" }
];

const appStoreSearchUrl = (name) =>
  `itms-apps://search.itunes.apple.com/WebObjects/MZSearch.woa/wa/search?media=software&term=${encodeURIComponent(name)}`;

const A = (id, name, category, symbol, start, end, url = "", favorite = false) => {
  const storeFallback = url.length === 0;
  return {
    id,
    name,
    category,
    symbol,
    colors: [start, end],
    url: storeFallback ? appStoreSearchUrl(name) : url,
    favorite,
    storeFallback
  };
};

export const APPS = [
  A("files", "Dosyalar", "Sistem", "▰", "#52baff", "#0877dc", "shareddocuments://", true),
  A("safari", "Safari", "Araçlar", "⌁", "#63d7ff", "#0878e9", "https://www.google.com/", true),
  A("mail", "Mail", "İletişim", "✉", "#48b9ff", "#0874dd", "mailto:", true),
  A("calendar", "Takvim", "Sistem", "21", "#ffffff", "#e9edf3", "calshow://", true),
  A("notes", "Notlar", "İş & Notlar", "▤", "#fff66b", "#f0b91e", "mobilenotes://", true),
  A("whatsapp", "WhatsApp", "İletişim", "◔", "#44df77", "#0ba94d", "https://wa.me/", true),
  A("settings", "Ayarlar", "Sistem", "⚙", "#b5bdc9", "#68717e", "App-Prefs://", true),
  A("github", "GitHub", "Geliştirme", "⌘", "#343943", "#07090d", "https://github.com/", true),
  A("cursor", "Cursor", "Geliştirme", "◆", "#252a31", "#060708", "https://cursor.com/", true),
  A("chatgpt", "ChatGPT", "Yapay Zekâ", "✺", "#3f4b4a", "#101817", "https://chatgpt.com/", true),

  A("assistant", "Assistant", "Yapay Zekâ", "●", "#ffffff", "#e5e8ed", "https://assistant.google.com/"),
  A("gemini", "Gemini", "Yapay Zekâ", "✦", "#7c7bff", "#ef5dc3", "https://gemini.google.com/"),
  A("kimi", "Kimi", "Yapay Zekâ", "K", "#12151c", "#030405", "https://www.kimi.com/"),
  A("meta-ai", "Meta AI", "Yapay Zekâ", "✺", "#f7f2ff", "#cbb8ff", "https://www.meta.ai/"),
  A("manus", "Manus", "Yapay Zekâ", "☝", "#ffffff", "#d9dbe0", "https://manus.im/"),
  A("grok-bot", "Grok Bot", "Yapay Zekâ", "◒", "#85878d", "#1d1f24", "https://grok.com/"),
  A("grok", "Grok", "Yapay Zekâ", "G", "#1e222b", "#020305", "https://grok.com/"),
  A("tilmo", "Tilmo", "Yapay Zekâ", "••", "#d6baff", "#8e65ea"),

  A("freeform", "Freeform", "İş & Notlar", "〽", "#52c8de", "#1d789d", "freeform://"),
  A("journal", "Günlük", "İş & Notlar", "◫", "#ca83ff", "#6748c7"),
  A("keynote", "Keynote", "İş & Notlar", "▣", "#65c6ff", "#177ac9", "https://www.icloud.com/keynote/"),
  A("goodnotes", "Goodnotes", "İş & Notlar", "≋", "#ffffff", "#c4e7ee", "https://www.goodnotes.com/"),
  A("notion", "Notion", "İş & Notlar", "N", "#ffffff", "#d8d8d8", "https://www.notion.so/"),
  A("notability", "Notability", "İş & Notlar", "▤", "#318de9", "#1454a2", "https://notability.com/"),
  A("obsidian", "Obsidian", "İş & Notlar", "◆", "#9a6cff", "#321469", "obsidian://open"),
  A("tasks", "Görevler", "İş & Notlar", "✓", "#75baff", "#2b6ee5", "https://tasks.google.com/"),
  A("lead-connector", "Lead Connector", "İş & Notlar", "L", "#ff774e", "#e03f20"),
  A("slack", "Slack", "İş & Notlar", "✣", "#f5f5f5", "#dcdde3", "https://slack.com/"),
  A("zight", "Zight", "İş & Notlar", "▶", "#4eb2ff", "#075cbc", "https://zight.com/"),
  A("web-clipper", "Web Clipper", "İş & Notlar", "✂", "#d5b0ff", "#7251bf"),
  A("linear", "Linear", "İş & Notlar", "◩", "#3f4147", "#121316", "https://linear.app/"),

  A("python-editor", "Python Editor", "Geliştirme", "Py", "#f7df62", "#3379b5"),
  A("tailscale", "Tailscale", "Geliştirme", "⠿", "#4b4e55", "#111317", "https://login.tailscale.com/admin"),
  A("godaddy", "GoDaddy", "Geliştirme", "G", "#343639", "#090a0c", "https://www.godaddy.com/"),
  A("creative-preview", "Creative Preview", "Geliştirme", "▣", "#6dd8b7", "#309096"),
  A("google-cloud", "Google Cloud", "Geliştirme", "☁", "#ffffff", "#cbd9eb", "https://console.cloud.google.com/"),
  A("google-admin", "Admin", "Geliştirme", "◆", "#6fa8ff", "#245bc2", "https://admin.google.com/"),
  A("cloud-search", "Cloud Search", "Geliştirme", "⌕", "#eaf3ff", "#a6cafa", "https://cloudsearch.google.com/"),

  A("telegram", "Telegram", "İletişim", "➤", "#53bcf5", "#1f83cf", "https://t.me/"),
  A("yahoo-mail", "Yahoo Mail", "İletişim", "Y!", "#8655f4", "#4721ad", "https://mail.yahoo.com/"),
  A("messages", "Mesajlar", "İletişim", "●", "#65e97f", "#11aa45", "sms:"),
  A("instagram", "Instagram", "İletişim", "◎", "#ff5d87", "#783fd2", "https://www.instagram.com/"),
  A("facetime", "FaceTime", "İletişim", "▰", "#56df7b", "#14a94a", "facetime://"),
  A("contacts", "Kişiler", "İletişim", "●", "#d6d4cb", "#87857e"),
  A("phone", "Telefon", "İletişim", "☎", "#62e377", "#14a340", "tel:"),

  A("viamichelin", "ViaMichelin", "Seyahat", "V", "#245d8c", "#09233b", "https://www.viamichelin.com/"),
  A("turkish-airlines", "Turkish Airlines", "Seyahat", "✈", "#df2938", "#96121e", "https://www.turkishairlines.com/"),
  A("pegasus", "Pegasus", "Seyahat", "✈", "#f7e167", "#ffffff", "https://www.flypgs.com/"),
  A("trip", "Trip.com", "Seyahat", "Trip", "#4f6cef", "#2635a7", "https://www.trip.com/"),
  A("db-navigator", "DB Navigator", "Seyahat", "DB", "#ffffff", "#dedede", "https://int.bahn.de/"),
  A("bahnbonus", "BahnBonus", "Seyahat", "DB", "#ef4949", "#ad1420", "https://int.bahn.de/"),
  A("museum-card", "MüzeKart", "Seyahat", "M", "#f6f3e7", "#7f6242", "https://muze.gov.tr/"),
  A("booking", "Booking.com", "Seyahat", "B", "#1553a4", "#082955", "https://www.booking.com/"),
  A("tripsy", "Tripsy", "Seyahat", "▣", "#ffbd50", "#e57719", "https://tripsy.app/"),
  A("marriott", "Marriott Bonvoy", "Seyahat", "M", "#ffffff", "#d9d7d2", "https://www.marriott.com/"),
  A("jump", "Jump", "Seyahat", "✈", "#aeeaff", "#55a7ef"),
  A("all-events", "AllEvents", "Seyahat", "ae", "#e6ffff", "#83ccd1", "https://allevents.in/"),

  A("apple-maps", "Harita", "Haritalar", "⌖", "#7ada8d", "#4d88ee", "https://maps.apple.com/"),
  A("google-maps", "Google Maps", "Haritalar", "⌖", "#ffffff", "#dfe9f2", "https://maps.google.com/"),
  A("waze", "Waze", "Haritalar", "☺", "#86e2ff", "#35add5", "https://www.waze.com/live-map/"),
  A("yandex-navi", "Yandex Navi", "Haritalar", "➤", "#fff09a", "#e6b72f", "https://yandex.com/maps/"),
  A("yandex-maps", "Yandex Maps", "Haritalar", "●", "#ffffff", "#efefef", "https://yandex.com/maps/"),
  A("radar-map", "Radar Haritası", "Haritalar", "⌾", "#9dd7f0", "#2f7ca4"),
  A("organic-maps", "Organic Maps", "Haritalar", "➤", "#62ba7b", "#28713d", "https://organicmaps.app/"),
  A("satellite-finder", "Satellite Finder", "Haritalar", "⌁", "#465aff", "#111872"),
  A("satellite-channels", "Satellite Channels", "Haritalar", "▧", "#ece7ff", "#aa9fe5"),

  A("podcasts", "Podcast’ler", "Medya", "◉", "#c55fff", "#7627bc", "podcasts://"),
  A("itunes-store", "iTunes Store", "Medya", "★", "#d85dff", "#8b29ce", "itms://"),
  A("apple-tv", "TV", "Medya", "tv", "#31343b", "#07090b", "videos://"),
  A("music", "Müzik", "Medya", "♫", "#ff5270", "#d80f42", "music://"),
  A("books", "Kitaplar", "Medya", "▥", "#ffae43", "#e36e12", "ibooks://"),
  A("netflix", "Netflix", "Medya", "N", "#261010", "#050505", "https://www.netflix.com/"),
  A("tiktok", "TikTok", "Medya", "♪", "#24272d", "#030405", "https://www.tiktok.com/"),
  A("twitch", "Twitch", "Medya", "▣", "#9f55ff", "#5b22b9", "https://www.twitch.tv/"),
  A("youtube", "YouTube", "Medya", "▶", "#ff3e45", "#c5000d", "https://www.youtube.com/"),
  A("youtube-music", "YouTube Music", "Medya", "▶", "#ff3850", "#b80017", "https://music.youtube.com/"),
  A("spotify", "Spotify", "Medya", "≋", "#36d768", "#0b842f", "https://open.spotify.com/"),
  A("shazam", "Shazam", "Medya", "S", "#4fa8ff", "#1261cd", "https://www.shazam.com/"),
  A("t24", "T24", "Medya", "T24", "#4a9fef", "#155aa0", "https://t24.com.tr/"),
  A("eversolo", "Eversolo Control", "Medya", "e", "#ffffff", "#cfd4da"),
  A("tv-plus", "TV+", "Medya", "TV+", "#30333a", "#090a0c", "https://www.tvplus.com.tr/"),

  A("camera", "Kamera", "Yaratıcılık", "●", "#c6d0da", "#59636f", "camera://"),
  A("photos", "Fotoğraflar", "Yaratıcılık", "✿", "#ffffff", "#d7dce4", "photos-redirect://"),
  A("garageband", "GarageBand", "Yaratıcılık", "♬", "#ffae39", "#e83a20"),
  A("imovie", "iMovie", "Yaratıcılık", "★", "#9864ed", "#5130a8"),
  A("sketchbook", "Sketchbook", "Yaratıcılık", "✎", "#e85f4c", "#98322a", "https://www.sketchbook.com/"),
  A("canva", "Canva", "Yaratıcılık", "C", "#48d1d2", "#6e56cf", "https://www.canva.com/"),
  A("playground", "Playground", "Yaratıcılık", "◉", "#4b505d", "#171920"),
  A("photo-booth", "Photo Booth", "Yaratıcılık", "▣", "#ef4a3f", "#a31318"),
  A("doa", "DOA", "Yaratıcılık", "◉", "#78b875", "#173f2a"),
  A("edge-gallery", "Edge Gallery", "Yaratıcılık", "✣", "#ffffff", "#d9ecff"),
  A("polycam", "Polycam", "Yaratıcılık", "⌂", "#ececf4", "#9aa2b2", "https://poly.cam/"),

  A("chrome", "Chrome", "Google", "●", "#f2f2f2", "#cfd2d7", "https://www.google.com/chrome/"),
  A("google-photos", "Google Fotoğraflar", "Google", "✣", "#ffffff", "#e1e3e7", "https://photos.google.com/"),
  A("google-calendar", "Google Takvim", "Google", "31", "#ffffff", "#dfe5ec", "https://calendar.google.com/"),
  A("google-docs", "Dokümanlar", "Google", "▤", "#63a4ff", "#2966d1", "https://docs.google.com/"),
  A("google-sheets", "E-Tablolar", "Google", "＋", "#5bc881", "#20824b", "https://sheets.google.com/"),
  A("google-one", "Google One", "Google", "1", "#ffffff", "#d9e7ff", "https://one.google.com/"),
  A("google-keep", "Google Keep", "Google", "●", "#fff26d", "#e9ba2a", "https://keep.google.com/"),
  A("authenticator", "Authenticator", "Google", "✕", "#ffffff", "#d9e4ed"),

  A("weather", "Hava Durumu", "Sistem", "☀", "#6fc4ff", "#277bc8", "weather://"),
  A("stocks", "Borsa", "Sistem", "⌁", "#4d525a", "#13161b", "stocks://"),
  A("find-my", "Bul", "Sistem", "◎", "#49e29d", "#168d55", "findmy://"),
  A("shortcuts", "Kestirmeler", "Sistem", "◆", "#9b4ee8", "#e2417b", "shortcuts://"),
  A("voice-memos", "Sesli Notlar", "Sistem", "≋", "#34373e", "#0c0e11"),
  A("measure", "Ölçüm", "Sistem", "╂", "#34373e", "#101215"),
  A("passwords", "Parolalar", "Sistem", "⚿", "#ffd957", "#2e87c7"),
  A("preview", "Önizleme", "Sistem", "◉", "#ffffff", "#d6e1ec"),
  A("health", "Sağlık", "Sistem", "♥", "#ffffff", "#e4e4e4", "x-apple-health://"),
  A("tips", "İpuçları", "Sistem", "●", "#ffd54b", "#e89f10", "tips://"),
  A("translate", "Çeviri", "Sistem", "A", "#72d8e0", "#238899", "translate://"),
  A("apple-store", "Apple Store", "Sistem", "▣", "#64d6ea", "#188aa8", "https://www.apple.com/tr/store"),
  A("clock", "Saat", "Sistem", "◷", "#ffffff", "#d8d8d8", "clock-alarm://"),
  A("feedback", "Geri Bildirim", "Sistem", "!", "#9d5ae6", "#5423a0", "applefeedback://"),

  A("firefox", "Firefox", "Araçlar", "◒", "#ff8559", "#7730a9", "https://www.mozilla.org/firefox/"),
  A("orbot", "Orbot", "Araçlar", "◐", "#c5afe8", "#7454a1"),
  A("expressvpn", "ExpressVPN", "Araçlar", "E", "#ef5c55", "#9d1f22", "https://www.expressvpn.com/"),
  A("moonlight", "Moonlight", "Araçlar", "◢", "#393f8e", "#151945", "https://moonlight-stream.org/"),
  A("ups", "UPS", "Araçlar", "UPS", "#6a4a2d", "#2a1a11", "https://www.ups.com/"),
  A("dropbox", "Dropbox", "Araçlar", "◆", "#1787ef", "#0750ac", "https://www.dropbox.com/"),
  A("fusion", "Fusion", "Araçlar", "◆", "#3a3d43", "#090a0d"),

  A("sahibinden", "sahibinden", "Alışveriş", "S", "#ffe739", "#e7c900", "https://www.sahibinden.com/"),
  A("dolap", "Dolap", "Alışveriş", "⌂", "#79c888", "#2f8255", "https://dolap.com/"),
  A("hepsiburada", "Hepsiburada", "Alışveriş", "hb", "#ff782f", "#cf4211", "https://www.hepsiburada.com/"),
  A("amazon", "Amazon", "Alışveriş", "a", "#ffcc72", "#eaa937", "https://www.amazon.com.tr/"),
  A("garanti", "Garanti BBVA", "Finans", "✣", "#3fca79", "#08703a", "https://www.garantibbva.com.tr/"),

  A("threads", "Threads", "Sosyal", "@", "#36383e", "#08090b", "https://www.threads.net/"),
  A("reddit", "Reddit", "Sosyal", "●", "#ff5a28", "#c92e09", "https://www.reddit.com/"),
  A("linkedin", "LinkedIn", "Sosyal", "in", "#317dc1", "#0b4d89", "https://www.linkedin.com/"),
  A("pinterest", "Pinterest", "Sosyal", "P", "#e93d48", "#a30917", "https://www.pinterest.com/"),

  A("sudoku", "Sudoku", "Oyunlar", "9", "#ffffff", "#ccd3db"),
  A("games", "Oyunlar", "Oyunlar", "🚀", "#ff716a", "#be2430"),
  A("kelimelik", "Kelimelik", "Oyunlar", "K", "#ffd955", "#ef9819"),

  A("apple-home", "Ev", "Akıllı Ev", "⌂", "#ffb54d", "#e16618", "com.apple.home://"),
  A("google-home", "Google Home", "Akıllı Ev", "⌂", "#ffffff", "#d9e6f1", "https://home.google.com/"),

  A("windows", "Windows", "Uzaktan Erişim", "▦", "#50a9e8", "#1262a4"),
  A("rustdesk", "RustDesk", "Uzaktan Erişim", "●", "#52c1d8", "#1c8097", "https://rustdesk.com/"),
  A("utm-remote", "UTM Remote", "Uzaktan Erişim", "▣", "#50d969", "#147b2c", "https://mac.getutm.app/"),
  A("teamviewer", "TeamViewer", "Uzaktan Erişim", "↔", "#466ed7", "#17358d", "https://www.teamviewer.com/"),
  A("anydesk", "AnyDesk", "Uzaktan Erişim", "◇", "#ff5b54", "#c62224", "https://anydesk.com/"),

  A("vscode", "VS Code", "Linux", "◱", "#3aa0f0", "#1b6fc2", "https://code.visualstudio.com/"),
  A("terminal", "Terminal", "Linux", "❯", "#3a3f47", "#111318"),
  A("gimp", "GIMP", "Linux", "◔", "#9a8d7a", "#5c5145", "https://www.gimp.org/"),
  A("inkscape", "Inkscape", "Linux", "◆", "#3a3f47", "#0c0d10", "https://inkscape.org/"),
  A("krita", "Krita", "Linux", "✎", "#4fb0ff", "#1f6fc0", "https://krita.org/"),
  A("blender", "Blender", "Linux", "◉", "#ff9a3c", "#e0700a", "https://www.blender.org/"),
  A("libreoffice", "LibreOffice", "Linux", "▤", "#3fbf3f", "#0f7a12", "https://www.libreoffice.org/"),
  A("vlc", "VLC", "Linux", "▲", "#ffb04d", "#e07a00", "https://www.videolan.org/vlc/"),
  A("obs-studio", "OBS Studio", "Linux", "◉", "#3a3a3e", "#131315", "https://obsproject.com/"),
  A("audacity", "Audacity", "Linux", "≋", "#4b6bff", "#0a1f8f", "https://www.audacityteam.org/"),
  A("kdenlive", "Kdenlive", "Linux", "▶", "#6f97d0", "#274f88", "https://kdenlive.org/"),
  A("steam", "Steam", "Linux", "◉", "#3a4150", "#0f1622", "https://store.steampowered.com/"),
  A("discord", "Discord", "Linux", "◔", "#7b84f5", "#4650e0", "https://discord.com/"),
  A("signal", "Signal", "Linux", "◔", "#5b63ff", "#2a34e0", "https://signal.org/"),
  A("thunderbird", "Thunderbird", "Linux", "✉", "#4aa0ff", "#0a6fe0", "https://www.thunderbird.net/"),
  A("docker", "Docker", "Linux", "◫", "#4aa8f0", "#1274c8", "https://www.docker.com/"),
  A("neovim", "Neovim", "Linux", "◆", "#6bc24a", "#2f7a1f", "https://neovim.io/"),
  A("flatpak", "Flatpak", "Linux", "◆", "#6aa8e0", "#2f6fb0", "https://flatpak.org/"),
  A("ubuntu", "Ubuntu", "Linux", "◉", "#ff7a4d", "#d13f14", "https://ubuntu.com/")
];
